version: '3.3'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: demoapp_local_django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    networks:
      - demo-app


  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: demoapp_production_postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - demo-app

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
    networks:
      - demo-app

  superset:
    image: amancevice/superset:0.25.6
    ports:
      - "8088:8088"
    volumes:
      - ./superset-conf/config:/etc/superset
      - ./superset-conf/data:/var/lib/superset
    networks:
      - demo-app

  nginx:
    image: nginx:1.15
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - demo-app
    depends_on:
      - django
      - superset

networks:
   demo-app:
